server:
  port: 8059
spring:
  application:
    name: service-statistics
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.100
  redis:
    host: 192.168.1.100
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    password: 123
    username: root
    url: jdbc:mysql://192.168.1.100:3306/cyc_edu?serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl